export const LOCALBIZ_CATEGORIES = [
  'Accounting & Tax',
  'Auto Repair & Services',
  'Beauty & Personal Care',
  'Cleaning Services',
  'Construction & Contractors',
  'Dental',
  'Education & Tutoring',
  'Events & Weddings',
  'Financial Services',
  'Fitness & Wellness',
  'Food & Restaurants',
  'Grocery & Markets',
  'Healthcare & Clinics',
  'Home Services',
  'Hotels & Hospitality',
  'IT & Technology Services',
  'Legal Services',
  'Logistics & Transportation',
  'Marketing & Creative',
  'Pet Services',
  'Plumbing',
  'Real Estate',
  'Retail',
  'Security Services',
  'Travel & Tourism',
] as const;

export type LocalBizCategory = (typeof LOCALBIZ_CATEGORIES)[number];
